#############################################################################
# Makefile for building: testQTCPserver
# Generated by qmake (3.1) (Qt 5.8.1)
# Project:  ../testTCPServer/testQTCPserver.pro
# Template: app
# Command: /usr/local/Qt-5.8.1/bin/qmake -o Makefile ../testTCPServer/testQTCPserver.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /usr/bin/gcc
CXX           = /usr/bin/g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../testTCPServer -I. -I/usr/local/Qt-5.8.1/include -I/usr/local/Qt-5.8.1/include/QtGui -I/usr/local/Qt-5.8.1/include/QtNetwork -I/usr/local/Qt-5.8.1/include/QtSerialPort -I/usr/local/Qt-5.8.1/include/QtCore -I. -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I/usr/local/Qt-5.8.1/mkspecs/devices/linux-rasp-pi-g++
QMAKE         = /usr/local/Qt-5.8.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = testQTCPserver1.0.0
DISTDIR = /home/pi/WorkSpace/daiphun/.tmp/testQTCPserver1.0.0
LINK          = /usr/bin/g++
LFLAGS        = -Wl,-rpath-link,/opt/vc/lib -Wl,-rpath-link,/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/lib/arm-linux-gnueabihf -mfloat-abi=hard -Wl,-O1 -Wl,-rpath,/usr/local/Qt-5.8.1/lib
LIBS          = $(SUBLIBS) -L/opt/vc/lib -L/usr/local/Qt-5.8.1/lib -lQt5Gui -lQt5Network -lQt5SerialPort -lQt5Core -lGLESv2 -lpthread 
AR            = /usr/bin/ar cqs
RANLIB        = 
SED           = sed
STRIP         = /usr/bin/strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../testTCPServer/main.cpp \
		../testTCPServer/fountainserver.cpp \
		../testTCPServer/simpleserialinterface.cpp \
		../testTCPServer/tcppackager.cpp \
		../testTCPServer/clienttcpsocket.cpp \
		../testTCPServer/communicationchecker.cpp \
		../testTCPServer/fountainserialpackager.cpp moc_fountainserver.cpp \
		moc_simpleserialinterface.cpp \
		moc_communicationchecker.cpp \
		moc_fountainserialpackager.cpp
OBJECTS       = main.o \
		fountainserver.o \
		simpleserialinterface.o \
		tcppackager.o \
		clienttcpsocket.o \
		communicationchecker.o \
		fountainserialpackager.o \
		moc_fountainserver.o \
		moc_simpleserialinterface.o \
		moc_communicationchecker.o \
		moc_fountainserialpackager.o
DIST          = /usr/local/Qt-5.8.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.8.1/mkspecs/common/unix.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/linux.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/sanitize.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.8.1/mkspecs/qdevice.pri \
		/usr/local/Qt-5.8.1/mkspecs/features/device_config.prf \
		/usr/local/Qt-5.8.1/mkspecs/devices/common/linux_device_pre.conf \
		/usr/local/Qt-5.8.1/mkspecs/devices/common/linux_device_post.conf \
		/usr/local/Qt-5.8.1/mkspecs/devices/common/linux_arm_device_post.conf \
		/usr/local/Qt-5.8.1/mkspecs/qconfig.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.8.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/usr/local/Qt-5.8.1/mkspecs/features/spec_post.prf \
		../testTCPServer/.qmake.stash \
		/usr/local/Qt-5.8.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/toolchain.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/qt.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/resources.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/moc.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/qmake_use.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/file_copies.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/lex.prf \
		../testTCPServer/testQTCPserver.pro ../testTCPServer/fountainserver.h \
		../testTCPServer/simpleserialinterface.h \
		../testTCPServer/tcppackager.h \
		../testTCPServer/clienttcpsocket.h \
		../testTCPServer/communicationchecker.h \
		../testTCPServer/fountainserialpackager.h ../testTCPServer/main.cpp \
		../testTCPServer/fountainserver.cpp \
		../testTCPServer/simpleserialinterface.cpp \
		../testTCPServer/tcppackager.cpp \
		../testTCPServer/clienttcpsocket.cpp \
		../testTCPServer/communicationchecker.cpp \
		../testTCPServer/fountainserialpackager.cpp
QMAKE_TARGET  = testQTCPserver
DESTDIR       = 
TARGET        = testQTCPserver


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../testTCPServer/testQTCPserver.pro /usr/local/Qt-5.8.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf /usr/local/Qt-5.8.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.8.1/mkspecs/common/unix.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/linux.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/sanitize.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.8.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.8.1/mkspecs/qdevice.pri \
		/usr/local/Qt-5.8.1/mkspecs/features/device_config.prf \
		/usr/local/Qt-5.8.1/mkspecs/devices/common/linux_device_pre.conf \
		/usr/local/Qt-5.8.1/mkspecs/devices/common/linux_device_post.conf \
		/usr/local/Qt-5.8.1/mkspecs/devices/common/linux_arm_device_post.conf \
		/usr/local/Qt-5.8.1/mkspecs/qconfig.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/local/Qt-5.8.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.8.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/usr/local/Qt-5.8.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt-5.8.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/toolchain.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/qt.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/resources.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/moc.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/qmake_use.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/file_copies.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.8.1/mkspecs/features/lex.prf \
		../testTCPServer/testQTCPserver.pro \
		/usr/local/Qt-5.8.1/lib/libQt5Gui.prl \
		/usr/local/Qt-5.8.1/lib/libQt5Network.prl \
		/usr/local/Qt-5.8.1/lib/libQt5SerialPort.prl \
		/usr/local/Qt-5.8.1/lib/libQt5Core.prl
	$(QMAKE) -o Makefile ../testTCPServer/testQTCPserver.pro
/usr/local/Qt-5.8.1/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.8.1/mkspecs/common/unix.conf:
/usr/local/Qt-5.8.1/mkspecs/common/linux.conf:
/usr/local/Qt-5.8.1/mkspecs/common/sanitize.conf:
/usr/local/Qt-5.8.1/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.8.1/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-5.8.1/mkspecs/common/g++-base.conf:
/usr/local/Qt-5.8.1/mkspecs/common/g++-unix.conf:
/usr/local/Qt-5.8.1/mkspecs/qdevice.pri:
/usr/local/Qt-5.8.1/mkspecs/features/device_config.prf:
/usr/local/Qt-5.8.1/mkspecs/devices/common/linux_device_pre.conf:
/usr/local/Qt-5.8.1/mkspecs/devices/common/linux_device_post.conf:
/usr/local/Qt-5.8.1/mkspecs/devices/common/linux_arm_device_post.conf:
/usr/local/Qt-5.8.1/mkspecs/qconfig.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt-5.8.1/mkspecs/modules/qt_lib_zlib_private.pri:
/usr/local/Qt-5.8.1/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.8.1/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.8.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf:
/usr/local/Qt-5.8.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Qt-5.8.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.8.1/mkspecs/features/toolchain.prf:
/usr/local/Qt-5.8.1/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.8.1/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.8.1/mkspecs/features/default_post.prf:
/usr/local/Qt-5.8.1/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.8.1/mkspecs/features/qt.prf:
/usr/local/Qt-5.8.1/mkspecs/features/resources.prf:
/usr/local/Qt-5.8.1/mkspecs/features/moc.prf:
/usr/local/Qt-5.8.1/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-5.8.1/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.8.1/mkspecs/features/qmake_use.prf:
/usr/local/Qt-5.8.1/mkspecs/features/file_copies.prf:
/usr/local/Qt-5.8.1/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.8.1/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.8.1/mkspecs/features/yacc.prf:
/usr/local/Qt-5.8.1/mkspecs/features/lex.prf:
../testTCPServer/testQTCPserver.pro:
/usr/local/Qt-5.8.1/lib/libQt5Gui.prl:
/usr/local/Qt-5.8.1/lib/libQt5Network.prl:
/usr/local/Qt-5.8.1/lib/libQt5SerialPort.prl:
/usr/local/Qt-5.8.1/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../testTCPServer/testQTCPserver.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Qt-5.8.1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../testTCPServer/fountainserver.h ../testTCPServer/simpleserialinterface.h ../testTCPServer/tcppackager.h ../testTCPServer/clienttcpsocket.h ../testTCPServer/communicationchecker.h ../testTCPServer/fountainserialpackager.h $(DISTDIR)/
	$(COPY_FILE) --parents ../testTCPServer/main.cpp ../testTCPServer/fountainserver.cpp ../testTCPServer/simpleserialinterface.cpp ../testTCPServer/tcppackager.cpp ../testTCPServer/clienttcpsocket.cpp ../testTCPServer/communicationchecker.cpp ../testTCPServer/fountainserialpackager.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Qt-5.8.1/mkspecs/features/data/dummy.cpp
	/usr/bin/g++ -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/local/Qt-5.8.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_fountainserver.cpp moc_simpleserialinterface.cpp moc_communicationchecker.cpp moc_fountainserialpackager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_fountainserver.cpp moc_simpleserialinterface.cpp moc_communicationchecker.cpp moc_fountainserialpackager.cpp
moc_fountainserver.cpp: /usr/local/Qt-5.8.1/include/QtNetwork/QTcpServer \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtcpserver.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtnetworkglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.8.1/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtnetwork-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.8.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.8.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.8.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qabstractsocket.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.8.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.8.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.8.1/include/QtCore/qset.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qhostaddress.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/QNetworkSession \
		/usr/local/Qt-5.8.1/include/QtNetwork/qnetworksession.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qnetworkinterface.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qnetworkconfiguration.h \
		/usr/local/Qt-5.8.1/include/QtCore/QDebug \
		/usr/local/Qt-5.8.1/include/QtCore/QDataStream \
		/usr/local/Qt-5.8.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.8.1/include/QtGui/QList \
		/usr/local/Qt-5.8.1/include/QtGui/qevent.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtguiglobal.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtgui-config.h \
		/usr/local/Qt-5.8.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.8.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.8.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.8.1/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.8.1/include/QtCore/qurl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.8.1/include/QtCore/qfile.h \
		/usr/local/Qt-5.8.1/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.8.1/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtouchdevice.h \
		../testTCPServer/clienttcpsocket.h \
		/usr/local/Qt-5.8.1/include/QtCore/QObject \
		/usr/local/Qt-5.8.1/include/QtNetwork/QTcpSocket \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtcpsocket.h \
		/usr/local/Qt-5.8.1/include/QtCore/QTimer \
		/usr/local/Qt-5.8.1/include/QtCore/qtimer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasictimer.h \
		../testTCPServer/fountainserver.h \
		moc_predefs.h \
		/usr/local/Qt-5.8.1/bin/moc
	/usr/local/Qt-5.8.1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Qt-5.8.1/mkspecs/devices/linux-rasp-pi-g++ -I/home/pi/WorkSpace/testTCPServer -I/usr/local/Qt-5.8.1/include -I/usr/local/Qt-5.8.1/include/QtGui -I/usr/local/Qt-5.8.1/include/QtNetwork -I/usr/local/Qt-5.8.1/include/QtSerialPort -I/usr/local/Qt-5.8.1/include/QtCore -I. -I/usr/include/c++/4.9 -I/usr/include/arm-linux-gnueabihf/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include ../testTCPServer/fountainserver.h -o moc_fountainserver.cpp

moc_simpleserialinterface.cpp: /usr/local/Qt-5.8.1/include/QtSerialPort/QSerialPort \
		/usr/local/Qt-5.8.1/include/QtSerialPort/qserialport.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.8.1/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.8.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.8.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.8.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.8.1/include/QtSerialPort/qserialportglobal.h \
		/usr/local/Qt-5.8.1/include/QtSerialPort/QSerialPortInfo \
		/usr/local/Qt-5.8.1/include/QtSerialPort/qserialportinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/QMap \
		/usr/local/Qt-5.8.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.8.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.8.1/include/QtCore/qset.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer_impl.h \
		../testTCPServer/simpleserialinterface.h \
		moc_predefs.h \
		/usr/local/Qt-5.8.1/bin/moc
	/usr/local/Qt-5.8.1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Qt-5.8.1/mkspecs/devices/linux-rasp-pi-g++ -I/home/pi/WorkSpace/testTCPServer -I/usr/local/Qt-5.8.1/include -I/usr/local/Qt-5.8.1/include/QtGui -I/usr/local/Qt-5.8.1/include/QtNetwork -I/usr/local/Qt-5.8.1/include/QtSerialPort -I/usr/local/Qt-5.8.1/include/QtCore -I. -I/usr/include/c++/4.9 -I/usr/include/arm-linux-gnueabihf/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include ../testTCPServer/simpleserialinterface.h -o moc_simpleserialinterface.cpp

moc_communicationchecker.cpp: /usr/local/Qt-5.8.1/include/QtCore/QObject \
		/usr/local/Qt-5.8.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.8.1/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.8.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.8.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.8.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/QProcess \
		/usr/local/Qt-5.8.1/include/QtCore/qprocess.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.8.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.8.1/include/QtCore/QDebug \
		/usr/local/Qt-5.8.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.8.1/include/QtCore/qset.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/QTimer \
		/usr/local/Qt-5.8.1/include/QtCore/qtimer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasictimer.h \
		/usr/local/Qt-5.8.1/include/QtGui/QRegExpValidator \
		/usr/local/Qt-5.8.1/include/QtGui/qvalidator.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtguiglobal.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtgui-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregularexpression.h \
		/usr/local/Qt-5.8.1/include/QtGui/QValidator \
		../testTCPServer/fountainserialpackager.h \
		/usr/local/Qt-5.8.1/include/QtCore/QString \
		../testTCPServer/communicationchecker.h \
		moc_predefs.h \
		/usr/local/Qt-5.8.1/bin/moc
	/usr/local/Qt-5.8.1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Qt-5.8.1/mkspecs/devices/linux-rasp-pi-g++ -I/home/pi/WorkSpace/testTCPServer -I/usr/local/Qt-5.8.1/include -I/usr/local/Qt-5.8.1/include/QtGui -I/usr/local/Qt-5.8.1/include/QtNetwork -I/usr/local/Qt-5.8.1/include/QtSerialPort -I/usr/local/Qt-5.8.1/include/QtCore -I. -I/usr/include/c++/4.9 -I/usr/include/arm-linux-gnueabihf/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include ../testTCPServer/communicationchecker.h -o moc_communicationchecker.cpp

moc_fountainserialpackager.cpp: /usr/local/Qt-5.8.1/include/QtCore/QObject \
		/usr/local/Qt-5.8.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.8.1/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.8.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.8.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.8.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/QString \
		../testTCPServer/fountainserialpackager.h \
		moc_predefs.h \
		/usr/local/Qt-5.8.1/bin/moc
	/usr/local/Qt-5.8.1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Qt-5.8.1/mkspecs/devices/linux-rasp-pi-g++ -I/home/pi/WorkSpace/testTCPServer -I/usr/local/Qt-5.8.1/include -I/usr/local/Qt-5.8.1/include/QtGui -I/usr/local/Qt-5.8.1/include/QtNetwork -I/usr/local/Qt-5.8.1/include/QtSerialPort -I/usr/local/Qt-5.8.1/include/QtCore -I. -I/usr/include/c++/4.9 -I/usr/include/arm-linux-gnueabihf/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include ../testTCPServer/fountainserialpackager.h -o moc_fountainserialpackager.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: ../testTCPServer/main.cpp /usr/local/Qt-5.8.1/include/QtCore/QCoreApplication \
		/usr/local/Qt-5.8.1/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.8.1/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.8.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.8.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.8.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qeventloop.h \
		../testTCPServer/fountainserver.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/QTcpServer \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtcpserver.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtnetworkglobal.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtnetwork-config.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qabstractsocket.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.8.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.8.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.8.1/include/QtCore/qset.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qhostaddress.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/QNetworkSession \
		/usr/local/Qt-5.8.1/include/QtNetwork/qnetworksession.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qnetworkinterface.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qnetworkconfiguration.h \
		/usr/local/Qt-5.8.1/include/QtCore/QDebug \
		/usr/local/Qt-5.8.1/include/QtCore/QDataStream \
		/usr/local/Qt-5.8.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.8.1/include/QtGui/QList \
		/usr/local/Qt-5.8.1/include/QtGui/qevent.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtguiglobal.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtgui-config.h \
		/usr/local/Qt-5.8.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.8.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.8.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.8.1/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.8.1/include/QtCore/qurl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.8.1/include/QtCore/qfile.h \
		/usr/local/Qt-5.8.1/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.8.1/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtouchdevice.h \
		../testTCPServer/clienttcpsocket.h \
		/usr/local/Qt-5.8.1/include/QtCore/QObject \
		/usr/local/Qt-5.8.1/include/QtNetwork/QTcpSocket \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtcpsocket.h \
		/usr/local/Qt-5.8.1/include/QtCore/QTimer \
		/usr/local/Qt-5.8.1/include/QtCore/qtimer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasictimer.h \
		../testTCPServer/simpleserialinterface.h \
		/usr/local/Qt-5.8.1/include/QtSerialPort/QSerialPort \
		/usr/local/Qt-5.8.1/include/QtSerialPort/qserialport.h \
		/usr/local/Qt-5.8.1/include/QtSerialPort/qserialportglobal.h \
		/usr/local/Qt-5.8.1/include/QtSerialPort/QSerialPortInfo \
		/usr/local/Qt-5.8.1/include/QtSerialPort/qserialportinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/QMap \
		../testTCPServer/communicationchecker.h \
		/usr/local/Qt-5.8.1/include/QtCore/QProcess \
		/usr/local/Qt-5.8.1/include/QtCore/qprocess.h \
		/usr/local/Qt-5.8.1/include/QtGui/QRegExpValidator \
		/usr/local/Qt-5.8.1/include/QtGui/qvalidator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregularexpression.h \
		/usr/local/Qt-5.8.1/include/QtGui/QValidator \
		../testTCPServer/fountainserialpackager.h \
		/usr/local/Qt-5.8.1/include/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../testTCPServer/main.cpp

fountainserver.o: ../testTCPServer/fountainserver.cpp ../testTCPServer/fountainserver.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/QTcpServer \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtcpserver.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtnetworkglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.8.1/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtnetwork-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.8.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.8.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.8.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qabstractsocket.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.8.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.8.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.8.1/include/QtCore/qset.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qhostaddress.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/QNetworkSession \
		/usr/local/Qt-5.8.1/include/QtNetwork/qnetworksession.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qnetworkinterface.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qnetworkconfiguration.h \
		/usr/local/Qt-5.8.1/include/QtCore/QDebug \
		/usr/local/Qt-5.8.1/include/QtCore/QDataStream \
		/usr/local/Qt-5.8.1/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.8.1/include/QtGui/QList \
		/usr/local/Qt-5.8.1/include/QtGui/qevent.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtguiglobal.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtgui-config.h \
		/usr/local/Qt-5.8.1/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.8.1/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.8.1/include/QtGui/qregion.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrect.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmargins.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsize.h \
		/usr/local/Qt-5.8.1/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.8.1/include/QtCore/qurl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.8.1/include/QtCore/qfile.h \
		/usr/local/Qt-5.8.1/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.8.1/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtouchdevice.h \
		../testTCPServer/clienttcpsocket.h \
		/usr/local/Qt-5.8.1/include/QtCore/QObject \
		/usr/local/Qt-5.8.1/include/QtNetwork/QTcpSocket \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtcpsocket.h \
		/usr/local/Qt-5.8.1/include/QtCore/QTimer \
		/usr/local/Qt-5.8.1/include/QtCore/qtimer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasictimer.h \
		/usr/local/Qt-5.8.1/include/QtCore/QTextCodec \
		/usr/local/Qt-5.8.1/include/QtCore/qtextcodec.h \
		/usr/local/Qt-5.8.1/include/QtCore/QJsonDocument \
		/usr/local/Qt-5.8.1/include/QtCore/qjsondocument.h \
		/usr/local/Qt-5.8.1/include/QtCore/qjsonvalue.h \
		/usr/local/Qt-5.8.1/include/QtCore/QJsonObject \
		/usr/local/Qt-5.8.1/include/QtCore/qjsonobject.h \
		../testTCPServer/tcppackager.h \
		/usr/local/Qt-5.8.1/include/QtCore/QCryptographicHash \
		/usr/local/Qt-5.8.1/include/QtCore/qcryptographichash.h \
		/usr/local/Qt-5.8.1/include/QtCore/QDateTime \
		/usr/local/Qt-5.8.1/include/QtCore/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fountainserver.o ../testTCPServer/fountainserver.cpp

simpleserialinterface.o: ../testTCPServer/simpleserialinterface.cpp ../testTCPServer/simpleserialinterface.h \
		/usr/local/Qt-5.8.1/include/QtSerialPort/QSerialPort \
		/usr/local/Qt-5.8.1/include/QtSerialPort/qserialport.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.8.1/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.8.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.8.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.8.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.8.1/include/QtSerialPort/qserialportglobal.h \
		/usr/local/Qt-5.8.1/include/QtSerialPort/QSerialPortInfo \
		/usr/local/Qt-5.8.1/include/QtSerialPort/qserialportinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/QMap \
		/usr/local/Qt-5.8.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.8.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.8.1/include/QtCore/qset.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/QDebug \
		/usr/local/Qt-5.8.1/include/QtCore/QElapsedTimer \
		/usr/local/Qt-5.8.1/include/QtCore/qelapsedtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simpleserialinterface.o ../testTCPServer/simpleserialinterface.cpp

tcppackager.o: ../testTCPServer/tcppackager.cpp ../testTCPServer/tcppackager.h \
		/usr/local/Qt-5.8.1/include/QtCore/QJsonDocument \
		/usr/local/Qt-5.8.1/include/QtCore/qjsondocument.h \
		/usr/local/Qt-5.8.1/include/QtCore/qjsonvalue.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.8.1/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.8.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.8.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.8.1/include/QtCore/QJsonObject \
		/usr/local/Qt-5.8.1/include/QtCore/qjsonobject.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.8.1/include/QtCore/QCryptographicHash \
		/usr/local/Qt-5.8.1/include/QtCore/qcryptographichash.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/QDateTime \
		/usr/local/Qt-5.8.1/include/QtCore/qdatetime.h \
		/usr/local/Qt-5.8.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringmatcher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcppackager.o ../testTCPServer/tcppackager.cpp

clienttcpsocket.o: ../testTCPServer/clienttcpsocket.cpp ../testTCPServer/clienttcpsocket.h \
		/usr/local/Qt-5.8.1/include/QtCore/QObject \
		/usr/local/Qt-5.8.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.8.1/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.8.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.8.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.8.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/QTcpSocket \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtcpsocket.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtnetworkglobal.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qtnetwork-config.h \
		/usr/local/Qt-5.8.1/include/QtNetwork/qabstractsocket.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.8.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.8.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.8.1/include/QtCore/qset.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clienttcpsocket.o ../testTCPServer/clienttcpsocket.cpp

communicationchecker.o: ../testTCPServer/communicationchecker.cpp ../testTCPServer/communicationchecker.h \
		/usr/local/Qt-5.8.1/include/QtCore/QObject \
		/usr/local/Qt-5.8.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.8.1/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.8.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.8.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.8.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/QProcess \
		/usr/local/Qt-5.8.1/include/QtCore/qprocess.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.8.1/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhash.h \
		/usr/local/Qt-5.8.1/include/QtCore/QDebug \
		/usr/local/Qt-5.8.1/include/QtCore/qdebug.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlocale.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvariant.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvector.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpoint.h \
		/usr/local/Qt-5.8.1/include/QtCore/qset.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/QTimer \
		/usr/local/Qt-5.8.1/include/QtCore/qtimer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasictimer.h \
		/usr/local/Qt-5.8.1/include/QtGui/QRegExpValidator \
		/usr/local/Qt-5.8.1/include/QtGui/qvalidator.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtguiglobal.h \
		/usr/local/Qt-5.8.1/include/QtGui/qtgui-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregularexpression.h \
		/usr/local/Qt-5.8.1/include/QtGui/QValidator \
		../testTCPServer/fountainserialpackager.h \
		/usr/local/Qt-5.8.1/include/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o communicationchecker.o ../testTCPServer/communicationchecker.cpp

fountainserialpackager.o: ../testTCPServer/fountainserialpackager.cpp ../testTCPServer/fountainserialpackager.h \
		/usr/local/Qt-5.8.1/include/QtCore/QObject \
		/usr/local/Qt-5.8.1/include/QtCore/qobject.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobal.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/Qt-5.8.1/include/QtCore/qconfig.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtcore-config.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlogging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qflags.h \
		/usr/local/Qt-5.8.1/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.8.1/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.8.1/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.8.1/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmutex.h \
		/usr/local/Qt-5.8.1/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.8.1/include/QtCore/qversiontagging.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstring.h \
		/usr/local/Qt-5.8.1/include/QtCore/qchar.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.8.1/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.8.1/include/QtCore/qlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.8.1/include/QtCore/qiterator.h \
		/usr/local/Qt-5.8.1/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-5.8.1/include/QtCore/qpair.h \
		/usr/local/Qt-5.8.1/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.8.1/include/QtCore/qregexp.h \
		/usr/local/Qt-5.8.1/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.8.1/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.8.1/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.8.1/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.8.1/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.8.1/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.8.1/include/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fountainserialpackager.o ../testTCPServer/fountainserialpackager.cpp

moc_fountainserver.o: moc_fountainserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fountainserver.o moc_fountainserver.cpp

moc_simpleserialinterface.o: moc_simpleserialinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_simpleserialinterface.o moc_simpleserialinterface.cpp

moc_communicationchecker.o: moc_communicationchecker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_communicationchecker.o moc_communicationchecker.cpp

moc_fountainserialpackager.o: moc_fountainserialpackager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fountainserialpackager.o moc_fountainserialpackager.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

